name: "PR Title Check"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR Title"
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            chore
          scopes: |
            dominion
            principles
            government
            covenant
            legislation
            project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
